name: asos-sct-onboarding-goliath-mriddell

trigger:
  branches:
    include:
      - main
      - feature/*

pr:
  branches:
    include:
      - main

pool:
    vmImage: ubuntu-latest

variables:
  slnPath: $(Build.SourcesDirectory)/CustomerService/CustomerWebApi.sln

steps: 
- task: DotNetCoreCLI@2
  displayName: 'Restore Nuget Packages'
  inputs:
    command: 'restore'
    projects: '$(slnPath)'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command : 'build'
    projects: '$(slnPath)'
    arguments: '-c Release'